CREATE TABLE Pledges (
   id INT AUTO_INCREMENT NOT NULL,
   first VARCHAR(200) NOT NULL,
   last VARCHAR(200) NOT NULL,
   company VARCHAR(200) NOT NULL,
   email VARCHAR(200) NOT NULL,
   state CHAR(2) ASCII NOT NULL,
   twitter VARCHAR(200) NOT NULL,
   PRIMARY KEY (id)
)